server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whitewise
    username: whitewise
    password: qwerpoiu12@@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update  # 필요한 경우에 맞게 'validate', 'create', 'create-drop' 등으로 변경 가능
    show-sql: true  # SQL 로그를 출력
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ''
      timeout: 2000
jwt:
  secret-key: TESG@!#$

springdoc:
  api-docs:
    path: /v3/api-docs
    # API 문서의 경로를 설정합니다.
  swagger-ui:
    path: /swagger-ui.html
    # Swagger UI 페이지의 경로를 설정합니다.

# 로깅 설정 (옵션)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE